### ISSUE TITLE
Error: Cannot query field "tab" on type "MdxFrontmatter"

### ISSUE THREAD

**Issue by evanmwillhite** [emulsify-ds/gatsby-theme-emulsify-workspace#7]
The error message `Cannot query field "tab" on type "MdxFrontmatter".` shows up if you haven't populated any components MDX files yet with that field in place.

## Short Term fix
1. Check for tab before using it

## Long Term fix
1. If "styleguide" or "components" directories aren't in place, give helpful feedback either via UI and/or CLI

┆Issue is synchronized with this [Jira Story](https://fourkitchens.atlassian.net/browse/GS-175) by [Unito](https://www.unito.io/learn-more)

**Comment by mirzu** [comment]
This is fixed by having the starter in place.
